baseURL = 'https://novel2430.github.io'
languageCode = 'en-us'
title = 'My Web | Wei, Feng'
theme = 'hugo-PaperMod'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    url = '/'
    weight = 5
  [[menus.main]]
    name = 'Notes'
    pageRef = '/notes'
    url = 'notes/'
    weight = 10
  [[menus.main]]
    name = 'Ideas'
    pageRef = '/ideas'
    url = 'ideas/'
    weight = 10
  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    url = 'tags/'
    weight = 20
  [[menus.main]]
    name = 'Archives'
    url = 'archives/'
    weight = 30
  [[menus.main]]
    name = 'Search'
    url = 'search/'
    weight = 30

[outputs]
  home = ['html', 'rss']
  page = ['html']
  rss = ['rss']
  section = ['html', 'rss']
  taxonomy = ['html', 'rss']
  term = ['html', 'rss']

[taxonomies]
  category = 'categories'
  tag = 'tags'

[markup]
  [markup.goldmark.extensions]
    definitionList = true
    linkify = true
    [markup.goldmark.extensions.cjk]
      eastAsianLineBreaks = false
      eastAsianLineBreaksStyle = 'simple'
      enable = false
      escapedSpace = false

[params]
  env = 'production'
  description = "Feng Wei's Web"
  author = 'Wei, Feng'
  defaultTheme = 'auto'
  # disableThemeToggle: true
  ShowShareButtons = false
  ShowReadingTime = true
  # disableSpecial1stPost: true
  displayFullLangName = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowAllPagesInArchive = true
  ShowPageNums = true
  ShowToc = true
  TocOpen = false
  mainSections = ['notes', 'ideas']
  [params.assets]
    favicon = '/img/favicon/favicon.ico'
    favicon16x16 = '/img/favicon/favicon16x16.png'
    favicon32x32 = '/img/favicon/favicon32x32.png'
    apple_touch_icon = '/img/favicon/apple-touch-icon.png'
  [params.homeInfoParams]
    Title = "👋 Welcome to my Web!"
    Content = "My Name is **Yu Wei, Feng**\n\n I will share my life here, such as some daily thoughts, notes, etc.\n\nFeel free to browse this site!\n\nMy native language is Chinese, but I will try my best to write the blog in English."
  [[params.socialIcons]]
    name = 'github'
    title = 'View My Github'
    url = 'https://github.com/novel2430'
  [[params.socialIcons]]
    name = 'Instagram'
    title = 'My Instagram'
    url = 'https://www.instagram.com/fongyuwei'
